'use client';
import { useRef, useState } from 'react';
import { AudioLines, Upload, ArrowUpRight, FileText, Download, Check, ChevronRight, Clock3, Users, ListChecks, ShieldCheck, X, LoaderCircle, Play, Sparkles } from 'lucide-react';
import Appearance from './components/appearance';
import { demoProtocol } from '@/lib/demo';
import { processAudio, waitForJob, validateAudio, PROCESSING_TIMEOUT_MS, type MeetingProtocol, type JobProgress } from '@/lib/contracts';
const stamp=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
export default function Home(){
 const [protocol,setProtocol]=useState<MeetingProtocol|null>(null),[file,setFile]=useState<File|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[exporting,setExporting]=useState(false),[demo,setDemo]=useState(false),[tab,setTab]=useState('overview'),[highlight,setHighlight]=useState<string[]>([]),[drag,setDrag]=useState(false);
 const [query,setQuery]=useState(''),[reviewOnly,setReviewOnly]=useState(false);
 const needle=query.trim().toLocaleLowerCase();
 const actions=protocol?.actionItems.filter(a=>(!reviewOnly||a.needsReview)&&[a.task,a.assignee,a.deadlineText,a.deadline].some(v=>v?.toLocaleLowerCase().includes(needle)))??[];
 const segments=protocol?.transcript.filter(s=>[s.text,s.speakerName,s.speakerId].some(v=>v?.toLocaleLowerCase().includes(needle)))??[];
 const [meetingTitle,setMeetingTitle]=useState(''),[meetingDate,setMeetingDate]=useState(''),[timeZone,setTimeZone]=useState(''),[progress,setProgress]=useState<JobProgress|null>(null);
 const stageLabels:Record<string,string>={uploading:'Аудио жіберілуде',queued:'Кезекте',preprocessing:'Аудионы тексеру',stt:'Сөйлеуді тану',diarization:'Сөйлеушілерді бөлу',alignment:'Репликаларды сәйкестендіру',extracting:'Тапсырмаларды анықтау',verifying:'Тапсырмаларды тексеру',summarizing:'Негізгі дәйексөздерді таңдау',done:'Хаттама дайын'};
 const input=useRef<HTMLInputElement>(null),controller=useRef<AbortController|null>(null);
 function choose(f?:File){if(!f)return; const message=validateAudio(f);setError(message??'');setFile(message?null:f);}
 async function submit(resume=false){if(!file&&!resume)return;setBusy(true);setError('');const c=new AbortController();controller.current=c;const timeout=setTimeout(()=>c.abort(),PROCESSING_TIMEOUT_MS);try{const result=resume&&progress?await waitForJob(progress.jobId,c.signal,setProgress):await processAudio(file!,c.signal,{title:meetingTitle||undefined,meetingDate:meetingDate||undefined,timeZone:timeZone||undefined},setProgress);setProtocol(result);setDemo(false);setTab('overview');}catch(e){setError(c.signal.aborted?'Күту тоқтатылды. Сервердегі тапсырма жалғасуы мүмкін.':e instanceof Error?e.message:'Өңдеу қатесі.');}finally{clearTimeout(timeout);setBusy(false);}}
 async function download(){if(!protocol)return;setExporting(true);setError('');try{const {exportProtocol}=await import('@/lib/export');await exportProtocol(protocol,demo);}catch{setError('Құжатты жасау мүмкін болмады. Қайта көріңіз.');}finally{setExporting(false);}}
 function source(ids:string[]){setQuery('');setHighlight(ids);setTab('transcript');setTimeout(()=>document.getElementById(ids[0])?.scrollIntoView({behavior:'smooth',block:'center'}),50);}
 function rename(id:string,name:string){setProtocol(p=>p?{...p,transcript:p.transcript.map(s=>s.speakerId===id?{...s,speakerName:name}:s)}:p);}
 return <div className="app"><aside className="sidebar"><a className="brand" href="/"><span className="logo"><AudioLines size={23}/></span>jinalys<span className="ai">AI</span></a><div className="workspace">ЖҰМЫС КЕҢІСТІГІ</div><button className="nav active" onClick={()=>{setProtocol(null);setQuery('');setReviewOnly(false);setError('');}}><FileText size={19}/> Жиналыс хаттамасы <ChevronRight size={15}/></button><div className="side-note"><ShieldCheck size={23}/><strong>Деректер өзіңізде</strong><p>Жергілікті AI модульдеріне қосуға арналған интерфейс.</p><span><i/> Сыртқы AI API қолданылмайды</span></div><div className="profile"><span className="avatar">JK</span><div>Жоба командасы<small>Хакатон · MVP</small></div><span className="version">v0.1</span></div></aside>
 <div className="main"><header><div>Жұмыс кеңістігі <ChevronRight size={14}/> <b>Жиналыс хаттамасы</b></div><span className="header-tag"><span className="dot"/> {demo&&protocol?'Демо режимі':'Прототип'}</span></header><main><div className="eyebrow">ЖИНАЛЫСТАН — НАҚТЫ ӘРЕКЕТКЕ</div><div className="title-row"><div><h1>Әр сөзден — нәтиже.</h1><p className="subtitle">Жиналыс жазбасынан қорытынды, тапсырмалар және дайын хаттама.</p></div><span className="language">ҚАЗ / РУС</span></div>
 <Appearance/>
 {!protocol&&<section className="meeting-fields"><label>Жиналыс атауы<input maxLength={200} value={meetingTitle} disabled={busy} onChange={e=>setMeetingTitle(e.target.value)}/></label><label>Жиналыс күні (белгісіз болса бос)<input type="date" value={meetingDate} disabled={busy} onChange={e=>setMeetingDate(e.target.value)}/></label><label>Уақыт белдеуі (IANA)<input placeholder="Asia/Almaty" maxLength={100} value={timeZone} disabled={busy} onChange={e=>setTimeZone(e.target.value)}/></label></section>}
 {!protocol&&progress&&<div className="job-status" role="status"><strong>{stageLabels[progress.stage]??(progress.stage.startsWith('chunk:')?'Мәтін бөлігі '+progress.stage.slice(6):progress.stage)}</strong><small>Тапсырма: {progress.jobId}. Бөліктердің өңдеу уақыты әртүрлі.</small>{!busy&&progress.status!=='completed'&&progress.status!=='failed'&&<button className="secondary" onClick={()=>void submit(true)}>Күтуді жалғастыру</button>}</div>}
 {error&&<div className="error" role="alert">{error}<button aria-label="Хабарламаны жабу" onClick={()=>setError('')}><X size={17}/></button></div>}
 {!protocol?<><section className="upload-card"><div className="section-heading"><span className="number">01</span><div><h2>Жиналыс жазбасын қосыңыз</h2><p>Алғашқы қадам — аудиофайлды жүктеу</p></div><span className="badge">MP3, WAV</span></div><div className={'dropzone '+(drag?'drag':'')} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!busy)choose(e.dataTransfer.files[0]);}}><div className="upload-icon"><Upload size={27}/></div><h3>{file?file.name:'Аудиофайлды осы жерге сүйреп әкеліңіз'}</h3><p>{file?`${(file.size/1024/1024).toFixed(1)} МБ · өңдеуге таңдалды`:'немесе компьютеріңізден таңдаңыз'}</p><button className="secondary" disabled={busy} onClick={()=>input.current?.click()}>Файлды таңдау <ArrowUpRight size={16}/></button><input ref={input} type="file" accept=".mp3,.wav" hidden onChange={e=>choose(e.target.files?.[0])}/><small>MP3 немесе WAV · 400 МБ дейін</small></div><div className="upload-bottom"><span><ShieldCheck size={16}/> Файл тек осы қолданбаның серверіне жіберіледі</span><button className="primary" disabled={!file||busy} onClick={()=>{setProgress(null);void submit();}}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={17}/>} {busy?'Өңделуде…':'Хаттама жасау'} {!busy&&<ChevronRight size={17}/>}</button></div>{busy&&<div className="processing" role="status">Өңдеу нәтижесін күтіп тұрмыз. Күтуді тоқтату сервердегі тапсырманы тоқтатпайды.<button onClick={()=>controller.current?.abort()}>Күтуді тоқтату</button></div>}</section>
 <section className="demo-card"><span className="demo-icon"><Play size={22}/></span><div><h3>Алдымен қалай жұмыс істейтінін көріңіз</h3><p>Дайын жиналыс үлгісі · 3 қатысушы · қазақша және орысша</p><small>Демо үлгісі: нақты аудио өңделмейді.</small></div><button disabled={busy} className="demo-button" onClick={()=>{setProtocol(structuredClone(demoProtocol));setDemo(true);setQuery('');setReviewOnly(false);setError('');setTab('overview');}}>Демоны ашу <ArrowUpRight size={17}/></button></section>
 <div className="how-title">БІР ЖАЗБА. ҮШ НӘТИЖЕ.</div><div className="features">{[{icon:FileText,title:'Толық транскрипт',text:'Сөйлеушілер мен уақыт белгілері бар жиналыс мәтіні.'},{icon:ListChecks,title:'Нақты тапсырмалар',text:'Не істеу керек, кім жауапты және қай мерзімге дейін.'},{icon:Download,title:'Дайын хаттама',text:'Қысқаша қорытынды және Word форматындағы құжат.'}].map((item,i)=><section className="feature" key={item.title}><div><item.icon size={21}/><span>0{i+1}</span></div><h3>{item.title}</h3><p>{item.text}</p></section>)}</div><p className="integration-note">Нақты өңдеу үшін жергілікті сервер мен speech/AI модельдері іске қосылуы керек.</p></>:<>
 <div className="result-heading"><div><span className="result-label">{demo?'ДЕМО ХАТТАМА':'ЖИНАЛЫС ХАТТАМАСЫ'}</span><h2>{protocol.title}</h2><p>{protocol.date??'Күні көрсетілмеген'} <span>·</span> {new Set(protocol.transcript.map(s=>s.speakerId)).size} қатысушы</p></div><div className="result-buttons"><button className="secondary" onClick={()=>{setProtocol(null);setQuery('');setReviewOnly(false);setFile(null);setError('');}}>Жаңа жиналыс</button><button className="primary" disabled={exporting} onClick={download}><Download size={17}/>{exporting?'Дайындалуда…':'DOCX жүктеу'}</button></div></div>
 {demo&&<div className="demo-notice"><Sparkles size={17}/> Бұл — алдын ала дайындалған үлгі. Нақты аудио өңделген жоқ.</div>}
 <div className="stats"><div><ListChecks/><strong>{protocol.actionItems.length}</strong><span>Тапсырма</span></div><div><Users/><strong>{new Set(protocol.transcript.map(s=>s.speakerId)).size}</strong><span>Қатысушы</span></div><div><Clock3/><strong>{protocol.actionItems.filter(a=>a.needsReview).length}</strong><span>Тексеру қажет</span></div></div>
 <div className="tabs" role="tablist" aria-label="Хаттама бөлімдері">{[['overview','Қорытынды'],['actions','Тапсырмалар'],['transcript','Толық мәтін']].map(([id,label])=><button role="tab" aria-selected={tab===id} className={tab===id?'selected':''} key={id} onClick={()=>setTab(id)}>{label}{id==='actions'&&<span>{protocol.actionItems.length}</span>}</button>)}</div>
 {(tab==='actions'||tab==='transcript')&&<div className="result-tools"><label className="search-label"><span>{tab==='actions'?'Тапсырма, жауапты немесе мерзім':'Мәтін немесе сөйлеуші'}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Іздеу…"/></label>{tab==='actions'&&<label className="review-toggle"><input type="checkbox" checked={reviewOnly} onChange={e=>setReviewOnly(e.target.checked)}/>Тек тексеру қажет</label>}<span className="match-count" role="status">{tab==='actions'?actions.length:segments.length} нәтиже</span>{(query||reviewOnly)&&<button className="secondary" onClick={()=>{setQuery('');setReviewOnly(false);}}>Тазалау</button>}</div>}
 {tab==='overview'&&<section className="content-card"><div className="card-title"><span className="small-icon"><FileText size={20}/></span><h3>Жиналыстың негізгі дәйексөздері</h3></div><p className="summary">{protocol.summary}</p><h4>Негізгі тақырыптар</h4><div className="topics">{protocol.topics.map((t,i)=><div key={i}><span><Check size={16}/></span><div><strong>{t.title}</strong><p>{t.summary}</p></div></div>)}</div><button className="text-button" onClick={()=>setTab('actions')}>Тапсырмаларды көру <ChevronRight size={16}/></button></section>}
 {tab==='actions'&&<section className="content-card actions">{actions.length===0?<p className="empty-results">Сәйкес тапсырма табылмады. Іздеуді немесе сүзгіні өзгертіңіз.</p>:actions.map((a,i)=><article key={a.id}><span className="task-index">{String(i+1).padStart(2,'0')}</span><div className="task-body"><div className="task-title"><h3>{a.task}</h3><span className={a.needsReview?'review':'confirmed'}>{a.needsReview?'Тексеру қажет':'Анықталған'}</span></div><div className="task-meta"><span><Users size={15}/>{a.assignee??'Жауапты анықталмаған'}</span><span><Clock3 size={15}/>{a.deadlineText??a.deadline??'Мерзім көрсетілмеген'}</span><span>AI бағасы (дәлдік емес): {Math.round(a.confidence*100)}%</span></div><button disabled={!a.sourceSegmentIds.length} className="text-button" onClick={()=>source(a.sourceSegmentIds)}>Дереккөзді көру <ArrowUpRight size={14}/></button></div></article>)}</section>}
 {tab==='transcript'&&<section className="content-card"><h3>Қатысушылардың аттары</h3><p className="muted">Өзгеріс транскриптке қолданылады. Тапсырмадағы жауаптыны бөлек тексеріңіз.</p><div className="speaker-inputs">{Array.from(new Set(protocol.transcript.map(s=>s.speakerId))).map(id=><label key={id}>{id}<input value={protocol.transcript.find(s=>s.speakerId===id)?.speakerName??''} placeholder="Қатысушының аты" onChange={e=>rename(id,e.target.value)}/></label>)}</div><div className="transcript">{segments.length===0&&<p className="empty-results">Сәйкес реплика табылмады. Басқа сөзбен іздеп көріңіз.</p>}{segments.map(s=><article id={s.id} key={s.id} className={highlight.includes(s.id)?'highlight':''}><time>{stamp(s.start)}</time><div><strong>{s.speakerName||s.speakerId}</strong><span className="lang-tag">{s.language??'—'}</span><p>{s.text}</p></div></article>)}</div></section>}
 </>}
 <footer><span className="footer-brand"><AudioLines size={16}/> JINALYS AI</span><span>Аз қол жұмысы. Көбірек нақтылық.</span><span>Хакатон прототипі / 2026</span></footer></main></div></div>;
}

